#!/bin/bash

# Based on https://github.com/sellerie98/Vibrance
# 
# Enter "./vibrance; %command% && ./vibrance" as launch options on csgo in Steam
#

if [$(nvidia-settings --query DigitalVibrance |grep 1023 |grep -v valid) == ""]
then
	nvidia-settings --assign [gpu:0]/DigitalVibrance[DP-3]=1023
	if [ $(echo $NV1) == ""]
		then
		echo "Vibrance Enabled (All)"
	fi
else
	nvidia-settings --assign [gpu:0]/DigitalVibrance[DP-3]=0
	if [$(nvidia-settings --query DigitalVibrance |grep 1023 |grep -v valid) != ""]
	then
		echo "Vibrance Disabled (All)"
	fi
fi